### ISSUE TITLE
Produce database for Deliverable 1

### ISSUE THREAD

**Issue by ccmothes** [rossyndicate/npca_wq#10]
Present data set in both spatial (.shp) and spreadsheet (.xlsx) formats

**Comment by kathryn-willi** [comment]
Very recently (late April), the EPA updated the ATTAINS database by aggregating the AU data to NHD high resolution catchments. This is very different than the older ATTAINS database I was building the workflow around (ATTAINS used to be based on the lower-resolution NHD Plus V2). Therefore, I am updating the workflow to be NHD HR based so we can use the most up-to-date data for Deliverable 1.
