### ISSUE TITLE
Deliverable 2: Water Quality Monitoring Handbook

### ISSUE THREAD

**Issue by ccmothes** [rossyndicate/npca_wq#5]
**SOW description:** 

A handbook on the network of water quality monitoring authorities and programs with a description of relevant agencies and
the collaboration or delegated authority to state or local agencies. The handbook should include:

- Guide on major data sources and water quality assessment tools

- Guide on where to find this data and these tools and how to use them

- An evaluation of available remote sensing data for both water quantity and quality

- Where available, download remote sensing products that can indicate water quality

- Recommendations on funding levels needed to support identified programs

<hr>

**Deadlines for Deliverable 2:**

**Week of June 30th** (before end of fiscal year): Meet with NPCA to discuss progress on Deliverable 2.

**Mid-August:** Katie sends out near-finalized Deliverable 2 + agenda for final meeting.

**Late August**: Meeting with NPCA to discuss final products. All deliverables completed.

**Comment by kathryn-willi** [comment]
- [x] Add an appendix writing out data dashboard hyperlinks + one-sentence description of what it is. 

- [x] Verify and write out where NPS-USGS funds and I&M WQ funds come from. Email Andrew Birch.

- [x] Remove first person language

- [x] Are there EPA dollars that go directly to NPS for WQ monitoring?

- [x] Add RS paragraph with @steeleb
